### PR TITLE
Add part on synthetic data

### PR DESCRIPTION
**Pull request by 14thibea**
This notebook explains how to use the command `generate`

### CODE REVIEW

**Comment by mdiazmel** [comment]
Hi @14thibea,

Sorry for the late revision of this PR. I was not aware of its existence. Next time please ping me if I'm not reactive enough!
BTW, will this notebook be included in [the clinicadl tutorial](https://aramislab.paris.inria.fr/clinicadl/tuto/intro.html) ?

**Comment by 14thibea** [comment]
Hi !

Actually the notebook was not ready so this is why I never told about it.
It is not working yet because there are some issues in the `generate` function of clinicadl, I made a new branch in my fork to fix them.
It would be great to add it !

**Comment by mdiazmel** [comment]
Ok, I see! 
Let me know when it will be ready or feel free to merge it to the main branch. We should see later how to integrate it to the tutorial.

**Comment by 14thibea** [comment]
Hi @mdiazmel !
I think the changes for clinicadl==0.2.0 are ready !

**Review by mdiazmel — APPROVED** [review]

**Pull request merged**
